$hyprmodule = $HOME/.config/hypr/modules/


source = $hyprmodule/keybinding.conf
source = $hyprmodule/startup.conf
source = $hyprmodule/monitor.conf
source = $hyprmodule/inputs.conf
source = $hyprmodule/animation.conf
source = $hyprmodule/windowrules.conf
source = $hyprmodule/general.conf
source = $hyprmodule/gesture.conf
