
general {
    gaps_in = 5
    gaps_out = 5
    border_size = 3
    col.active_border = rgba(c6a0f6ee) rgba(8aadf4ee) 45deg
    col.inactive_border = rgba(595959aa)
    resize_on_border=true
    layout = dwindle
}

misc {
    disable_hyprland_logo = yes
}

decoration {
    rounding = 10
    active_opacity = 0.95
    inactive_opacity = 0.8
    fullscreen_opacity = 1

    blur {
        enabled = true
        size = 6
        passes = 1
        new_optimizations = true
        popups = true
        special = true
        ignore_opacity = true
        xray = false

    }
}







# dwindle {
  
  #  pseudotile = yes 
  #  preserve_split = yes 
# }
