#Variables
input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 1
    touchpad {
        natural_scroll = yes
       drag_lock = 0
    }
    scroll_factor = 4
    sensitivity = 0.4 
}