windowrule = float on, match:class ^(sublime_text)$

windowrule = opacity 0.8 0.8, match:class ^(kitty)$
windowrule = opacity 0.8 0.8, match:class ^(thunar)$
windowrule = opacity 0.8 0.8, match:class ^(Code)$

windowrule = float on, center on, match:title ^(Open Files\|Open\|Save\|Save As\|Export\|Import\|Choose File\|Rename)$, match:class ^(.*)$


windowrule = float on, center on, match:class ^(blueman-manager)$
windowrule = float on, center on, match:class ^(org\.gnome\.gedit)$


windowrule = float on, center on, match:class ^(subl)$
windowrule = opacity 0.8 0.8, match:class ^(warbar)$


 

windowrule = opacity 0.94 0.94, match:class ^(rofi)$ # for app drawer
layerrule = blur on, match:namespace rofi # for app drawer
layerrule = blur on, ignore_alpha 0.5, match:namespace logout_dialog 
windowrule = opacity 0.94 0.94, match:class ^(logout_dialog)$ 
layerrule = animation popin, match:namespace rofi

layerrule = blur on,match:namespace waybar

layerrule = dim_around on, match:namespace wofi # for wofi

